version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./log:/var/log/nginx
    depends_on:
    - auth-server
    - diary-server
    - music-server

     auth-server:
        container_name: auth-server
        ports:
            - "8081:8081"
            build: ./auth-server
        restart: always
             diary-server:
        container_name: diary-server
        ports:
            - "8082:8082"
            build: ./diary-server
        restart: always
             music-server:
        container_name: music-server
        ports:
            - "8083:8083"
            build: ./music-server
        restart: always


